import Foundation

/// Generates RSS 2.0 feed files from published drafts.
enum PublishFeedGenerator {

    private static let feedDir: URL = {
        let dir = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Documents/SwiftMaestro Feeds", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }()

    static func defaultOutputURL(feedName: String) -> URL {
        feedDir.appendingPathComponent("\(slugify(feedName)).rss")
    }

    private static func rfc822String(from date: Date) -> String {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone.current
        formatter.dateFormat = "EEE, dd MMM yyyy HH:mm:ss Z"
        return formatter.string(from: date)
    }

    /// Write (or overwrite) a feed file containing the supplied drafts.
    static func writeFeed(
        feedName: String,
        outputURL: URL? = nil,
        drafts: [PublishDraft],
        history: [PublishHistoryEntry]
    ) throws -> URL {
        let slug = slugify(feedName)
        let outputURL = outputURL ?? feedDir.appendingPathComponent("\(slug).rss")

        let feedURL = URL(fileURLWithPath: outputURL.path)
            .absoluteString
            .addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? outputURL.path

        var itemsXML = ""
        let sortedDrafts = drafts.sorted { ($0.publishedAt ?? $0.modifiedAt) > ($1.publishedAt ?? $1.modifiedAt) }
        for draft in sortedDrafts {
            itemsXML += itemXML(for: draft, feedURL: feedURL)
        }

        let xml = """
        <?xml version="1.0" encoding="UTF-8"?>
        <rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
          <channel>
            <title>\(escaped(feedName))</title>
            <link>\(feedURL)</link>
            <description>Feed generated by SwiftMaestro Publish</description>
            <lastBuildDate>\(rfc822String(from: Date()))</lastBuildDate>
            \(itemsXML)
          </channel>
        </rss>
        """

        try xml.write(to: outputURL, atomically: true, encoding: .utf8)
        return outputURL
    }

    private static func itemXML(for draft: PublishDraft, feedURL: String) -> String {
        let pubDate = rfc822String(from: draft.publishedAt ?? draft.modifiedAt)
        let categories = draft.tags.map { "<category>\(escaped($0))</category>" }.joined(separator: "\n      ")
        let enclosureXML = draft.assetPaths.first.flatMap { makeEnclosureXML(for: $0) } ?? ""

        return """
          <item>
            <title>\(escaped(draft.title))</title>
            <link>\(feedURL)#\(escaped(draft.id))</link>
            <guid isPermaLink="false">\(escaped(draft.id))</guid>
            <pubDate>\(pubDate)</pubDate>
            \(categories)
            \(enclosureXML)
            <description>\(escaped(draft.summary))</description>
            <content:encoded><![CDATA[\(draft.bodyHTML)]]></content:encoded>
          </item>

        """
    }

    private static func makeEnclosureXML(for path: String) -> String {
        let url = URL(fileURLWithPath: path)
        guard FileManager.default.fileExists(atPath: path) else { return "" }
        guard let attrs = try? FileManager.default.attributesOfItem(atPath: path),
              let size = attrs[.size] as? Int else { return "" }
        let ext = url.pathExtension.lowercased()
        let mime: String
        switch ext {
        case "mp3": mime = "audio/mpeg"
        case "mp4", "m4v": mime = "video/mp4"
        case "mov": mime = "video/quicktime"
        case "png": mime = "image/png"
        case "jpg", "jpeg": mime = "image/jpeg"
        case "gif": mime = "image/gif"
        case "webp": mime = "image/webp"
        case "pdf": mime = "application/pdf"
        default: mime = "application/octet-stream"
        }
        let fileURL = url.absoluteString.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? path
        return "<enclosure url=\"\(fileURL)\" length=\"\(size)\" type=\"\(mime)\" />"
    }

    private static func escaped(_ text: String) -> String {
        text.replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
    }

    private static func slugify(_ text: String) -> String {
        let allowed = CharacterSet.alphanumerics
        return text.lowercased()
            .components(separatedBy: allowed.inverted)
            .filter { !$0.isEmpty }
            .joined(separator: "-")
    }
}
