#!/bin/bash
# Package script for SwiftMaestro
# Creates .dmg installer for distribution

set -e

echo "=========================================="
echo "SwiftMaestro Package Script"
echo "=========================================="
echo ""

# Version from git tag or default
VERSION="${VERSION:-1.0.0}"
APP_NAME="SwiftMaestro"
BUILD_DIR="build/Release"
APP_PATH="$BUILD_DIR/$APP_NAME.app"
DMG_NAME="$APP_NAME-$VERSION.dmg"

# Check if app exists
if [ ! -d "$APP_PATH" ]; then
    echo "❌ App not found at $APP_PATH"
    echo "Run ./scripts/build.sh first"
    exit 1
fi

echo "📦 Creating DMG: $DMG_NAME"
echo ""

# Create temporary directory for DMG contents
TEMP_DIR=$(mktemp -d)
mkdir -p "$TEMP_DIR/$APP_NAME.app"

# Copy app to temp
cp -R "$APP_PATH" "$TEMP_DIR/"

# Create symlink to Applications
ln -s /Applications "$TEMP_DIR/Applications"

# Create background image for DMG (simple blue gradient)
echo "🎨 Creating DMG background..."
cat > "$TEMP_DIR/.background" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>window-position</key>
    <string>{100, 100}</string>
    <key>window-size</key>
    <string>{600, 400}</string>
    <key>icon-size</key>
    <integer>80</integer>
    <key>background-color</key>
    <string>#2C3E50</string>
</dict>
</plist>
EOF

# Set up icon positions
cat > "$TEMP_DIR/.DS_Store" << 'EOF'
# This will be generated by Finder, but we set defaults
EOF

# Create the DMG
echo "📝 Creating disk image..."
hdiutil create -volname "$APP_NAME" \
               -srcfolder "$TEMP_DIR" \
               -ov -format UDZO \
               "$DMG_NAME"

# Verify DMG
echo "✅ Verifying DMG..."
hdiutil verify "$DMG_NAME"

# Clean up temp directory
rm -rf "$TEMP_DIR"

echo ""
echo "=========================================="
echo "✅ Package complete!"
echo "=========================================="
echo ""
echo "📦 Distribution package: $DMG_NAME"
echo "📊 Size: $(du -h "$DMG_NAME" | cut -f1)"
echo ""
echo "To test:"
echo "  open $DMG_NAME"
echo ""
echo "To distribute:"
echo "  - Upload $DMG_NAME to GitHub Releases"
echo "  - Users can drag $APP_NAME.app to /Applications"
echo ""
